# Generated by Django 4.1.9 on 2023-06-25 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="_type",
            field=models.CharField(
                choices=[("H", "Hitman"), ("M", "Manager"), ("BB", "Big Boss")],
                default="H",
                max_length=2,
                verbose_name="User type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(default="", max_length=255, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="user",
            name="in_charge_of",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_hits",
            field=models.ManyToManyField(blank=True, to="users.hit"),
        ),
    ]
