# Generated by Django 4.1.9 on 2023-06-26 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_hit_user__type_user_description_user_in_charge_of_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hit",
            name="assigned_hitman",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_hitman",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hit",
            name="description",
            field=models.CharField(default="", max_length=255, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="hit",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Name of User"),
        ),
        migrations.AddField(
            model_name="hit",
            name="state",
            field=models.CharField(
                choices=[("U", "Unassigned"), ("A", "Assigned"), ("F", "Failed"), ("C", "Completed")],
                default="U",
                max_length=2,
                verbose_name="User type",
            ),
        ),
    ]
